#!/usr/bin/env python3
"""
Correlation ID propagation – distributed tracing for OIG Proxy.

This module provides correlation ID generation and propagation across
all proxy layers: transport, telemetry, and twin.

Key features:
- Generate correlation ID at frame entry
- Propagate through transport, telemetry, and twin
- Ensure ID survives retries and failovers
- Log correlation ID at key decision points
- Auto-generate ID if not present

Usage:
    from correlation_id import get_correlation_id, set_correlation_id, clear_correlation_id
    from correlation_id import correlation_id_context, generate_correlation_id

    # Generate and set correlation ID
    cid = generate_correlation_id()
    set_correlation_id(cid)

    # Or use context manager
    with correlation_id_context() as cid:
        # All operations within this block share the same correlation ID
        process_frame(frame)

    # Get current correlation ID (auto-generates if not set)
    cid = get_correlation_id()

    # Clear when done
    clear_correlation_id()
"""

from __future__ import annotations

import contextvars
import logging
import secrets
import time
import uuid
from contextlib import contextmanager
from typing import Any, Generator

logger = logging.getLogger(__name__)

# Context variable for correlation ID (thread-safe and async-safe)
_correlation_id_var: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "correlation_id", default=None
)

# Prefix for correlation IDs generated by this proxy
CORR_ID_PREFIX = "oig"


def generate_correlation_id() -> str:
    """
    Generate a unique correlation ID.

    Format: oig_<timestamp>_<random_hex>
    Example: oig_1704067200_a3f7b2d9

    Returns:
        Unique correlation ID string
    """
    timestamp = int(time.time())
    random_part = secrets.token_hex(4)
    return f"{CORR_ID_PREFIX}_{timestamp}_{random_part}"


def generate_short_correlation_id() -> str:
    """
    Generate a short unique correlation ID (for compact logging).

    Format: oig_<random_hex>
    Example: oig_a3f7b2d9

    Returns:
        Short unique correlation ID string
    """
    return f"{CORR_ID_PREFIX}_{secrets.token_hex(4)}"


def get_correlation_id() -> str:
    """
    Get the current correlation ID.

    If no correlation ID is set, auto-generates one and logs a warning.

    Returns:
        Current correlation ID (auto-generated if not set)
    """
    cid = _correlation_id_var.get()
    if cid is None:
        cid = generate_correlation_id()
        _correlation_id_var.set(cid)
        logger.debug("CORR_ID: Auto-generated correlation ID: %s", cid)
    return cid


def get_correlation_id_optional() -> str | None:
    """
    Get the current correlation ID if set, None otherwise.

    Returns:
        Current correlation ID or None
    """
    return _correlation_id_var.get()


def set_correlation_id(correlation_id: str | None) -> None:
    """
    Set the correlation ID for the current context.

    Args:
        correlation_id: The correlation ID to set, or None to clear
    """
    _correlation_id_var.set(correlation_id)


def clear_correlation_id() -> None:
    """
    Clear the correlation ID from the current context.
    """
    _correlation_id_var.set(None)


@contextmanager
def correlation_id_context(
    correlation_id: str | None = None,
) -> Generator[str, None, None]:
    """
    Context manager for correlation ID propagation.

    Automatically generates a correlation ID if not provided.
    Clears the correlation ID when exiting the context.

    Args:
        correlation_id: Optional correlation ID to use (auto-generated if None)

    Yields:
        The correlation ID being used

    Example:
        with correlation_id_context() as cid:
            logger.info("Processing frame", extra={"correlation_id": cid})
            process_frame(frame)
    """
    cid = correlation_id or generate_correlation_id()
    token = _correlation_id_var.set(cid)
    try:
        yield cid
    finally:
        _correlation_id_var.reset(token)


@contextmanager
def correlation_id_context_frame(
    frame_data: bytes | str | None = None,
) -> Generator[str, None, None]:
    """
    Context manager specifically for frame processing.

    Generates a correlation ID based on frame content if possible,
    otherwise generates a random one.

    Args:
        frame_data: Optional frame data to derive correlation ID from

    Yields:
        The correlation ID being used
    """
    if frame_data is not None:
        # Try to extract a deterministic ID from frame content
        try:
            if isinstance(frame_data, bytes):
                frame_str = frame_data[:100].decode("utf-8", errors="ignore")
            else:
                frame_str = str(frame_data)[:100]

            # Include frame content hash in correlation ID for traceability
            import hashlib

            frame_hash = hashlib.sha256(frame_str.encode()).hexdigest()[:8]
            timestamp = int(time.time())
            cid = f"{CORR_ID_PREFIX}_{timestamp}_{frame_hash}"
        except Exception:
            cid = generate_correlation_id()
    else:
        cid = generate_correlation_id()

    token = _correlation_id_var.set(cid)
    try:
        yield cid
    finally:
        _correlation_id_var.reset(token)


def with_correlation_id(func: Any) -> Any:
    """
    Decorator to ensure a correlation ID is set for the function execution.

    If no correlation ID is set, auto-generates one.

    Args:
        func: Function to wrap

    Returns:
        Wrapped function
    """
    import functools

    @functools.wraps(func)
    def wrapper(*args: Any, **kwargs: Any) -> Any:
        cid = _correlation_id_var.get()
        if cid is None:
            cid = generate_correlation_id()
            token = _correlation_id_var.set(cid)
            try:
                return func(*args, **kwargs)
            finally:
                _correlation_id_var.reset(token)
        else:
            return func(*args, **kwargs)

    return wrapper


def log_with_correlation_id(
    message: str,
    level: int = logging.INFO,
    extra: dict[str, Any] | None = None,
) -> None:
    """
    Log a message with correlation ID included.

    Args:
        message: Log message
        level: Log level (default INFO)
        extra: Extra fields to include in log record
    """
    cid = get_correlation_id()
    extra = extra or {}
    extra["correlation_id"] = cid
    logger.log(level, message, extra=extra)


def format_log_message(
    message: str,
    correlation_id: str | None = None,
) -> str:
    """
    Format a log message with correlation ID prefix.

    Args:
        message: Original message
        correlation_id: Optional correlation ID (uses current if not provided)

    Returns:
        Formatted message with correlation ID
    """
    cid = correlation_id or get_correlation_id()
    return f"[{cid}] {message}"


class CorrelationIdMixin:
    """
    Mixin class to add correlation ID support to any class.

    Classes inheriting from this mixin get access to correlation ID
    methods and automatic propagation.
    """

    def __init__(self) -> None:
        self._correlation_id: str | None = None

    @property
    def correlation_id(self) -> str:
        """Get current correlation ID (auto-generates if not set)."""
        if self._correlation_id is None:
            self._correlation_id = get_correlation_id()
        return self._correlation_id

    @correlation_id.setter
    def correlation_id(self, value: str | None) -> None:
        """Set correlation ID."""
        self._correlation_id = value

    def log_with_cid(
        self,
        message: str,
        level: int = logging.INFO,
    ) -> None:
        """Log message with correlation ID."""
        formatted = format_log_message(message, self._correlation_id)
        logger.log(level, formatted)


def propagate_correlation_id_to_dict(
    data: dict[str, Any],
    correlation_id: str | None = None,
) -> dict[str, Any]:
    """
    Add correlation ID to a dictionary.

    Args:
        data: Dictionary to add correlation ID to
        correlation_id: Optional correlation ID (uses current if not provided)

    Returns:
        Dictionary with correlation_id field added
    """
    cid = correlation_id or get_correlation_id()
    result = dict(data)
    result["correlation_id"] = cid
    return result


def extract_correlation_id_from_dict(
    data: dict[str, Any],
    default: str | None = None,
) -> str | None:
    """
    Extract correlation ID from a dictionary.

    Args:
        data: Dictionary to extract from
        default: Default value if not found

    Returns:
        Correlation ID or default
    """
    return data.get("correlation_id", default)
